// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlHd5QJ0oYc_iR7nGVuQgTmuVLie08rHc',
    appId: '1:245063836374:web:5a1826686a16f897fa5f77',
    messagingSenderId: '245063836374',
    projectId: 'ndproject-743d6',
    authDomain: 'ndproject-743d6.firebaseapp.com',
    storageBucket: 'ndproject-743d6.appspot.com',
    measurementId: 'G-W8LR5B2ZGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFGiCR8o2W1ZpxRDGUYFCLn5gSo2FagpI',
    appId: '1:245063836374:android:005ca4a4c309c9fbfa5f77',
    messagingSenderId: '245063836374',
    projectId: 'ndproject-743d6',
    storageBucket: 'ndproject-743d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA38Act5RO9bmS4QapX2O7vFcdm_xpBU0k',
    appId: '1:245063836374:ios:dd429393c5640b37fa5f77',
    messagingSenderId: '245063836374',
    projectId: 'ndproject-743d6',
    storageBucket: 'ndproject-743d6.appspot.com',
    iosBundleId: 'com.example.christianSns',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA38Act5RO9bmS4QapX2O7vFcdm_xpBU0k',
    appId: '1:245063836374:ios:ea9c0eed4e85da1dfa5f77',
    messagingSenderId: '245063836374',
    projectId: 'ndproject-743d6',
    storageBucket: 'ndproject-743d6.appspot.com',
    iosBundleId: 'com.example.christianSns.RunnerTests',
  );
}
